src/main/java/com/sagg/domain/Story.java
package com.sagg.domain;

import java.io.Serializable;
import java.util.Date;
import java.util.UUID;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.compass.annotations.Searchable;
import org.compass.annotations.SearchableId;
import org.compass.annotations.SearchableProperty;

import com.sagg.exception.ValidationFailedBatchException;
import com.sagg.exception.ValidationFailedException;
import com.sagg.util.Globals;
import com.sagg.util.StringUtil;
import com.sagg.util.URLUtil;

@Entity
@Table(name="STORY")
@Searchable
public class Story extends DomainObject implements Serializable {

	private static final long serialVersionUID = 1L;
	private String url;
	private String title;
	private String description;
	private String thumbnailUrl;
	//private Collection<Tag> tags;
	private int voteUp;
	private int voteDown;
	private int spamFlags;
	private User createdBy;
	
	private Date created;
	private Date updated;
	
//    @Id
//    @GeneratedValue(strategy=GenerationType.AUTO)
//    @Column(name = "ID")
//    @SearchableId
//	public Integer getId() {
//		return id;
//	}
	
	public Story() {
	}

	public Story(int id, String url, String title, String description) {
		this(url, title, description);
		setId(id);
	}

	public Story(String url, String title, String description) {
		this.url = url;
		this.title = title;
		this.description = description;
	}

	@Column(name = "URL", nullable = false, length = Globals.MAX_STORY_URL_LENGTH)
	@SearchableProperty
	public String getUrl() {
		return url;
	}
	
	public void setUrl(String url) {
		this.url = url;
	}
	
	@Column(name = "TITLE", nullable = false, length = Globals.MAX_STORY_TITLE_LENGTH)
	@SearchableProperty
	public String getTitle() {
		return title;
	}
	
	public void setTitle(String title) {
		this.title = title;
	}
	
	@Column(name = "DESCRIPTION", nullable = false, length = Globals.MAX_STORY_DESCRIPTION_LENGTH)
	@SearchableProperty
	public String getDescription() {
		return description;
	}
	
	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "THUMBNAIL_URL", nullable = true, length = Globals.MAX_STORY_THUMBNAIL_URL_LENGTH)
	public String getThumbnailUrl() {
		return thumbnailUrl;
	}
	
	public void setThumbnailUrl(String thumbnailUrl) {
		this.thumbnailUrl = thumbnailUrl;
	}

	public int getVoteUp() {
		return voteUp;
	}

	public void setVoteUp(int voteUp) {
		this.voteUp = voteUp;
	}

	public int getVoteDown() {
		return voteDown;
	}

	public void setVoteDown(int voteDown) {
		this.voteDown = voteDown;
	}

	public int getSpamFlags() {
		return spamFlags;
	}

	public void setSpamFlags(int spamFlags) {
		this.spamFlags = spamFlags;
	}

	@ManyToOne
	@JoinColumn(name = "user_id")
	public User getCreatedBy() {
		return createdBy;
	}
	
	public void setCreatedBy(User createdBy) {
		this.createdBy = createdBy;
	}

	@PrePersist
	public void onCreate() {
		this.created = new Date();
	}

	@Temporal(TemporalType.TIMESTAMP)
	public Date getCreated() {
		return created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@PreUpdate
	public void onUpdate() {
		this.updated = new Date();
	}

	@Temporal(TemporalType.TIMESTAMP)
	public Date getUpdated() {
		return updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}
	
	@Transient
	public String getCompoundId() {
		return ((title == null ? "" : title.replaceAll("\\W", "-")).toLowerCase() + "-" + id).replaceAll("[-]+", "-"); 
	}
	
	@Transient
	public String getRandomUuid() {
		return UUID.randomUUID().toString();
	}
	
	public void validate() throws ValidationFailedBatchException {
		ValidationFailedBatchException exceptions = new ValidationFailedBatchException();
		if (StringUtil.isEmpty(this.url)) {
			exceptions.addException(new ValidationFailedException("url", "err.url_empty", "*** URL can not be empty. ***"));
			
		} else if (this.url.length() > Globals.MAX_STORY_URL_LENGTH) {
			exceptions.addException(new ValidationFailedException("url", "err.url_too_long", 
					new String[] { "" + Globals.MAX_STORY_URL_LENGTH }, "*** URL is too long. ***"));
			
		} else if (!URLUtil.isValidUrl(url)) {
			exceptions.addException(new ValidationFailedException("url", "err.url_invalid", 
					new String[] { url }, "*** Invalid URL ***"));
		}
		if (StringUtil.isEmpty(this.title)) {
			exceptions.addException(new ValidationFailedException("title", "err.title_empty", "*** Title can not be empty. ***"));
		}
		if (this.title.length() > Globals.MAX_STORY_TITLE_LENGTH) {
			exceptions.addException(new ValidationFailedException("title", "err.title_too_long", 
					new String[] { "" + Globals.MAX_STORY_TITLE_LENGTH }, "*** Title is too long. ***"));
		}
		if (StringUtil.isEmpty(this.description)) {
			exceptions.addException(new ValidationFailedException("description", "err.description_empty", 
					"*** Description can not be empty. ***"));
		}
		if (this.description.length() > Globals.MAX_STORY_DESCRIPTION_LENGTH) {
			exceptions.addException(new ValidationFailedException("description", "err.description_too_long", 
					new String[] { "" + Globals.MAX_STORY_DESCRIPTION_LENGTH }, "*** Description is too long. ***"));
		}
	}

}

src/main/java/com/sagg/domain/User.java
package com.sagg.domain;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.sagg.exception.ValidationFailedException;
import com.sagg.util.Globals;
import com.sagg.util.EmailUtil;
import com.sagg.util.StringUtil;

@Entity
@Table(name="USERS")
public class User extends DomainObject implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	private String email;
	private String username;
	private String password;
	private Integer type;
	private Boolean active;
	private Collection<Vote> votes;
	private Collection<Story> stories;
	private Collection<Bookmark> bookmarks;
    
    public User() {
    	type = Globals.USER_TYPE_REGULAR;
    }

	@Column(name = "EMAIL", unique=true, nullable = false, length = Globals.MAX_USER_EMAIL_LENGTH)
	public String getEmail() {
		return email;
	}
	
	public void setEmail(String email) {
		this.email = (email != null) ? email.trim() : null;
	}
	
	@Column(name = "USERNAME", unique=true, nullable = true, length = Globals.MAX_USER_USERNAME_LENGTH)
	public String getUsername() {
		return username;
	}
	
	public void setUsername(String name) {
		this.username = (name != null) ? name.trim() : null;
	}
	
	@Column(name = "PASSWORD", nullable = false, length = Globals.MAX_USER_PASSWORD_LENGTH)
	public String getPassword() {
		return password;
	}
	
	public void setPassword(String password) {
		this.password = password;
	}
	
	@Column(name = "TYPE", nullable = false)
	public Integer getType() {
		return type;
	}
	
	public void setType(Integer type) {
		this.type = type;
	}

	public Boolean getActive() {
		return active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}
	
	@OneToMany(cascade = {CascadeType.MERGE, CascadeType.REMOVE, CascadeType.REFRESH}, fetch=FetchType.EAGER, mappedBy="user")
	//TODO: JPA 2.0 supports new annotation: @MapKeyColumn(name="story_id") to create a Map<story_id, Vote> rather than a set
	public Collection<Vote> getVotes() {
		return votes;
	}
	
	//TODO: Mmm... think harder about redesigning this approach :(
	@Transient
	public Map<Integer, Vote> getVotesMap() { // Map<storyId, vote>
		return new HashMap<Integer, Vote>() {
			private static final long serialVersionUID = 1L;
			public Vote get(Object storyId) {
				Collection<Vote> votes = getVotes();
				if (votes != null) {
					for (Vote vote : votes) {
						if (storyId.equals(vote.getStory().getId())) {
							return vote;
						}
					}
				}
				return null;
			}
		};
	}
	
	@Transient
	public Collection<Vote> getVotesUp() {
		Collection<Vote> votesUp = new ArrayList<Vote>();
		if (votes != null) {
			for (Vote vote : votes) {
				if (vote.getVoteDirection().equals(Globals.VOTE_UP)) {
					votesUp.add(vote);
				}
			}
		}
		return votesUp;
	}
	
	@Transient
	public Collection<Vote> getVotesDown() {
		Collection<Vote> votesDown = new ArrayList<Vote>();
		if (votes != null) {
			for (Vote vote : votes) {
				if (vote.getVoteDirection().equals(Globals.VOTE_DOWN)) {
					votesDown.add(vote);
				}
			}
		}
		return votesDown;
	}

	public void setVotes(Collection<Vote> votes) {
		this.votes = votes;
	}

	@OneToMany(cascade = CascadeType.ALL, mappedBy="createdBy")
	public Collection<Story> getStories() {
		return stories;
	}
	
	public void setStories(Collection<Story> stories) {
		this.stories = stories;
	}
	
	@OneToMany(cascade = /*CascadeType.ALL*/ {CascadeType.MERGE, CascadeType.REMOVE, CascadeType.REFRESH}, fetch=FetchType.LAZY, mappedBy="user")
	public Collection<Bookmark> getBookmarks() {
		return bookmarks;
	}

	public void setBookmarks(Collection<Bookmark> bookmarks) {
		this.bookmarks = bookmarks;
	}
	
	@Transient
	public Collection<Story> getBookmarkedStories() {
		Collection<Story> stories = new ArrayList<Story>();
		for (Bookmark bookmark : bookmarks) {
			stories.add(bookmark.getStory());
		}
		return stories;
	}
	
	@Transient
	public Map<Integer, Bookmark> getBookmarksMap() {
		return new HashMap<Integer, Bookmark>() {
			private static final long serialVersionUID = 1L;
			public Bookmark get(Object storyId) {
				Collection<Bookmark> bookmarks = getBookmarks();
				if (bookmarks != null) {
					for (Bookmark bookmark : bookmarks) {
						if (storyId.equals(bookmark.getStory().getId())) {
							return bookmark;
						}
					}
				}
				return null;
			}
		};
	}

	//TODO: Move the validation methods out of the domain objects (UserValidator)
	//      This would make the code cleaner and allow us to have different validators for 
	//      the same object - it may be helpful sometimes. 
	public void validate() throws ValidationFailedException {
		if (!EmailUtil.isValidEmail(this.email)) {
			throw new ValidationFailedException("user.email", "err.email_invalid", "*** Invalid email. ***");
		}
		if (this.email.length() > Globals.MAX_USER_EMAIL_LENGTH) {
			throw new ValidationFailedException("user.email", "err.email_too_long", new String[]{""+Globals.MAX_USER_EMAIL_LENGTH}, "*** Email is too long. ***");
		}
		if (StringUtil.isEmpty(this.password)) {
			throw new ValidationFailedException("user.password", "err.password_empty", "*** Password can not be empty. ***");
		}
		if (this.password.length() > Globals.MAX_USER_PASSWORD_LENGTH) {
			throw new ValidationFailedException("user.password", "err.password_too_long", new String[]{""+Globals.MAX_USER_PASSWORD_LENGTH}, "*** Password is too long. ***");
		}
	}
	
	public String toString() {
		return this.email;
	}

}

src/main/java/com/sagg/domain/Vote.java
package com.sagg.domain;

import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

@Entity
@Table(name="VOTE")
public class Vote extends DomainObject implements Serializable {

	private static final long serialVersionUID = 1L;
	private User user;
	private Story story;
	private Integer voteDirection;
	
	public Vote() {
	}

	public Vote(User user, Story story, Integer voteDirection) {
		this.user = user;
		this.story = story;
		this.voteDirection = voteDirection;
	}

	@ManyToOne
	@JoinColumn(name = "user_id")
	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@ManyToOne
	@JoinColumn(name = "story_id")
	public Story getStory() {
		return story;
	}

	public void setStory(Story story) {
		this.story = story;
	}

	public Integer getVoteDirection() {
		return voteDirection;
	}

	public void setVoteDirection(Integer vote) {
		this.voteDirection = vote;
	}
	
}

src/main/webapp/WEB-INF/jsp/story/ajaxList.jsp
<%@ page contentType="text/html; charset=UTF-8" isELIgnored="false" %>

<%@ include file="/WEB-INF/jsp/includes.jsp" %>

	<c:forEach var="story" items="${stories}">
	<li class="resultsList">
		<div id="vote-story-${story.id}" class="voteContainer">
			<%@ include file="/WEB-INF/jsp/story/vote.jsp" %>
		</div>
		<div class="resultImage">
			<%-- <a href="<c:url value="/story/show?id=${story.compoundId}"/>">  --%>
			<a href="${story.url}">
				<c:choose>
					<c:when test="${empty(story.thumbnailUrl)}">
						<img src="<c:url value="/images/thumbnail_default.jpg"/>" alt="Story Screenshot" class="resultImage"/>
					</c:when>
					<c:otherwise>
						<img src="<c:url value="/thumbnails/${story.thumbnailUrl}.jpg"/>" alt="Story Screenshot" class="resultImage"/>
					</c:otherwise>
				</c:choose>
			</a>
		</div>
		<div class="resultStory">
			<%-- <a href="<c:url value="/story/show?id=${story.compoundId}"/>" class="resultTitle">  --%>
			<h2 class="resultTitle">
				<a href="${story.url}">
					<c:out value="${story.title}"/>
				</a>
				<c:if test="${userSession.valid}">
					<c:set var="bookmarkId" value="${userSession.user.bookmarksMap[story.id].id}"/>
					<img src="<c:choose><c:when test="${!empty(bookmarkId)}"><c:url value="/images/fav.png"/></c:when>
								<c:otherwise><c:url value="/images/fav_gray.png"/></c:otherwise></c:choose>" 
						alt='<fmt:message key="bookmark"/>' 
						onclick="bookmark('${story.id}', this); return false;"
						class="bookmark"/>
					<input type="hidden" id="bookmark-story-${story.id}" value="${bookmarkId}"/>
				</c:if>
			</h2>
			<p class="resultDescription">
				<c:out value="${story.description}"/>
			</p>
			<p class="resultAddedDate">
				<fmt:message key="added"/>: 
				<fmt:formatDate value="${story.created}" pattern="MMM dd, yyyy"/>
				
				<c:if test="${!empty story.createdBy.username}">
					<fmt:message key="by"/> <c:out value="${story.createdBy.username}"/>
				</c:if>
				
				&nbsp;&nbsp;
				
				<c:if test="${userSession.valid && !empty story.createdBy && userSession.user.email eq story.createdBy.email}">
					<a href='<c:url value="/story/create"/>?storyId=${story.id}'><fmt:message key="edit"/></a>
					<a href='#' onclick="confirmDelete('${story.id}')"><fmt:message key="delete"/></a>
				</c:if>

				<c:if test="${userSession.valid}">
					<a onclick="flagAsSpam(${story.id}, this)" class="flagAsSpam"><fmt:message key="flag_as_spam"/></a>
				</c:if>
			</p>
		</div>
	</li>
	</c:forEach>

src/main/webapp/WEB-INF/jsp/story/confirmDeletePopup.jsp
<%@ include file="/WEB-INF/jsp/includes.jsp" %>

<div id="confirmDeletePopupId">
	<p style="padding:10px; padding-bottom:20px;">
		<fmt:message key="confirm_delete_story_msg"/>
	</p>
	
	<input type="button" onclick="confirmYes();" value="<fmt:message key="yes"/>" class="button" style="margin:5px;"/>
	<input type="button" onclick="confirmNo();" value="<fmt:message key="no"/>" class="button" style="margin:5px;"/>
</div>

<script type="text/javascript">
	var storyId;
	var popup;
	
	$(document).ready(function() {
		popup = $("#confirmDeletePopupId").dialog({
			autoOpen : false,
			height : 170,
			width  : 400,
			modal  : true,
			resizable : false,
			draggable : true,
			title: '<fmt:message key="confirm_delete"/>'
		});
	});

	function confirmDelete(id) {
		storyId = id;
		$("#confirmDeletePopupId").dialog('open');
	}

	function confirmYes() {
		<c:url value="/story/delete" var="url">
			<c:param name="redirect" value="/main/${sessionScope.actionPath}"/>
		</c:url>
		document.location.href = '<c:out value="${url}"/>&storyId='+storyId;
	}

	function confirmNo() {
		$("#confirmDeletePopupId").dialog('close');
	}
</script>

src/main/webapp/WEB-INF/jsp/story/create.jsp
<%@ include file="/WEB-INF/jsp/includes.jsp" %>
<%@ include file="/WEB-INF/jsp/header.jsp" %>

<c:if test="${empty(userSession) || userSession.invalid}">
	<script type="text/javascript">
		$(function() {
			authPopup(true);
		});
	</script>	
</c:if>


<div id="main">

<h1><fmt:message key="add_link"/></h1>

<form:form modelAttribute="story" method="POST">

<form:hidden path="id"/>
<table class="form" style="padding:10px; padding-bottom: 15px;">
	<tr>
		<td class="formLabel"><fmt:message key="url"/>:</td>
		<td><form:input path="url" cssClass="formInputVeryWide" maxlength="${maxUrlLength + 50}" onkeyup="loadTitle(this.value);"/></td>
	</tr>
	<tr>
		<td></td>
		<td><form:errors path="url" cssClass="errors"/></td>
	</tr>
	
	
	<tr>
		<td class="formLabel"><fmt:message key="title"/>:</td>
		<td><form:input path="title" id="pageTitle" cssClass="formInputWide" maxlength="${maxTitleLength + 50}" onkeyup="titleKeypress();"/></td>
	</tr>
	<tr>
		<td></td>
		<td><form:errors path="title" cssClass="errors"/></td>
	</tr>
	
	
	<tr>
		<td class="formLabel"><fmt:message key="description"/>:</td>
		<td><form:textarea path="description" id="description" cssClass="formInputVeryWide formInputHigh"/></td>
	</tr>
	<tr>
		<td></td>
		<td class="errors">
			<form:errors path="description" cssClass="errors"/>
		</td>
	</tr>
	<tr>
		<td></td>
		<td>
			<span id="descriptionLimitText"></span>
		</td>
	</tr>
</table>
<br/>


<div style="padding-left:15px; padding-bottom:40px;">
	<input type="button" value='<c:choose><c:when test="${empty story.id}"><fmt:message key="add"/></c:when><c:otherwise><fmt:message key="save"/></c:otherwise></c:choose>' class="button" onclick="addStory(this);">
	<input type="button" value='<fmt:message key="cancel"/>' class="button" onclick="document.location.href = '<c:url value="/"/>'">
</div>

<script type="text/javascript">
var currentRequestNumber = 0;
var titleEnteredManually = false;

function titleKeypress() {
	titleEnteredManually = (document.getElementById('pageTitle').value.trim() != "");
}

function loadTitle(urlToGet) {
	if (titleEnteredManually) {
		return;
	}
	currentRequestNumber += 1;
	var request = currentRequestNumber;
	$.ajax({
		type: 'GET',
		url: '<c:url value="/story/getTitle"/>',
		data: "url=" + urlToGet,
		contentType: "application/x-www-form-urlencoded;charset=UTF-8",
		dataType: "html",
		success: function(data) {
			loadTitleSuccess(data.trim(), request);
		}
	});
}

function loadTitleSuccess(title, requestNo) {
	//This makes sure the requests get executed in the sequence 
	//in which they're called:
	if (requestNo >= currentRequestNumber) {
		document.getElementById('pageTitle').value = title;
	}
}





function addStory(addButton) {
	<c:if test="${empty(userSession) || userSession.invalid}">
		loginCallback = function(onAuthPopupCloseFunc) {
			addStoryContinued(addButton);
		};
		authPopup(false);
		return;
	</c:if>
	addStoryContinued(addButton);
}

function addStoryContinued(addButton) {
	addButton.onclick = null;
	document.forms[0].submit();
}
</script>
</form:form>
	
</div>



<c:set var="additionalHeadContent" value="/WEB-INF/jsp/story/descInputLimit_js.jsp"/>

<%@ include file="/WEB-INF/jsp/footer.jsp" %>

src/main/webapp/WEB-INF/jsp/story/descInputLimit_js.jsp
<%@ include file="/WEB-INF/jsp/includes.jsp" %>

<script src="<c:url value="/script/jquery/inputlimiter/jquery.inputlimiter.js"/>" type="text/javascript"></script>

<script type="text/javascript">
	$(document).ready(function() {
		$('#description').inputlimiter({
			limit: 500,
			boxId: 'descriptionLimitText',
			limitTextShow: false,
			remTextHideOnBlur: false,
			boxAttach: false
		});
	});
</script>

src/main/webapp/WEB-INF/jsp/story/flag_js.jsp
<script type="text/javascript">
function flagAsSpam(storyId, aTag) {
	aTag.onclick = null;
	$.ajax({ 
		url: "<c:url value="/story/flag"/>?storyId=" + storyId,
		type: "GET", 
		success: function(data) {
			//TODO: Handle success
			// i.e. briefly display a floating div saying something like "the
			// story has been flagged as spam and the admins will be notified"
		}
	});
}
</script>

src/main/webapp/WEB-INF/jsp/story/show.jsp
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<%@ include file="/WEB-INF/jsp/includes.jsp" %>

<?xml version="1.0"?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">

<head>
	<link rel="stylesheet" href="<c:url value="/styles/main.css"/>" type="text/css"/>
	<link rel="stylesheet" href="<c:url value="/styles/new.css"/>" type="text/css"/>
	
	<script src="<c:url value="/script/jquery/jquery-1.4.2.min.js"/>" type="text/javascript"></script> 
	<script src="<c:url value="/script/jquery/ui/jquery.ui.min.js"/>" type="text/javascript"></script> 
	<link href="<c:url value="/script/jquery/ui/jquery.ui.css"/>" type="text/css" rel="stylesheet"/> 
</head>

<body style="margin:0; padding:0;">

<%@ include file="/WEB-INF/jsp/authPopup.jsp" %>
<%@ include file="/WEB-INF/jsp/story/vote_js.jsp" %>

<div class="hoverPane voteContainer">
	<div style="float:top; display: block">
		&nbsp;
		<a href="${story.url}" class="ui-icon ui-icon-closethick" style="float:right;"></a>
		<a href="<c:url value="/story/list"/>" class="ui-icon ui-icon-arrowreturnthick-1-w" style="float:right;"></a>
	</div>
	<div id="vote-story-${story.id}" style="float:left; display: block">
		<%@ include file="/WEB-INF/jsp/story/vote.jsp" %>
	</div>
</div>

<iframe src="${story.url}" width="100%" height="100%" frameBorder="0">
	<p><fmt:message key="err.iframe"/></p>
</iframe>


</body>

</html>

src/main/webapp/WEB-INF/jsp/story/vote.jsp
<%@ include file="/WEB-INF/jsp/includes.jsp" %>

<%@ page contentType="text/html; charset=UTF-8" isELIgnored="false" %>
<c:set var="vote" value="${userSession.user.votesMap[story.id]}"/>

<c:choose>
	<c:when test="${empty(vote)}">
		<div style="display: block; height: 25px;">
			<div class="voteButtonContainer">
				<a onclick="vote(${story.id}, 1, this)" class="voteImage voteUpImage"></a>
			</div> 
			<div class="voteCountContainer"><c:out value="${story.voteUp}"/></div>
		</div>
		<div style="display: block; margin: 5px;">
			<fmt:message key="vote"/>
		</div>
		<div style="display: block; height: 25px;">
			<div class="voteButtonContainer">
				<a onclick="vote(${story.id}, -1, this)" class="voteImage voteDownImage"></a>
			</div>
			<div class="voteCountContainer"><c:out value="${story.voteDown}"/></div>
		</div>
	</c:when>
	<c:otherwise>
		<div style="display: block; min-height: 25px;">
			<c:choose>
				<c:when test="${vote.voteDirection > 0}">
					<div class="voteButtonContainer"><a class="voteImage voteUpImageDark"></a></div>
				</c:when>
				<c:otherwise>
					<div class="voteButtonContainer"><a class="voteImage voteUpImageDisabled"></a></div>
				</c:otherwise>
			</c:choose>
			<div class="voteCountContainer"><c:out value="${story.voteUp}"/></div>
		</div>
		<div style="display: block; margin: 4px;">
			<a onclick="vote(${story.id}, 0, this)" style="cursor:pointer;"><fmt:message key="unvote"/></a>
		</div>
		<div style="display: block; height: 25px;">
			<c:choose>
				<c:when test="${vote.voteDirection < 0}">
					<div class="voteButtonContainer"><a class="voteImage voteDownImageDark"></a></div>
				</c:when>
				<c:otherwise>
					<div class="voteButtonContainer"><a class="voteImage voteDownImageDisabled"></a></div>
				</c:otherwise>
			</c:choose>
			<div class="voteCountContainer"><c:out value="${story.voteDown}"/></div>
		</div>
	</c:otherwise>
</c:choose>

src/main/webapp/WEB-INF/jsp/story/vote_js.jsp
<script type="text/javascript">
var loginCallback = null;

function vote(storyId, direction, aTag) {
	<c:if test="${!userSession.valid}">
		loginCallback = function(onAuthPopupCloseFunc) {
			voteContinued(storyId, direction, aTag, onAuthPopupCloseFunc);
		};
		authPopup(false);
		return;
	</c:if>
	voteContinued(storyId, direction, aTag);
}

function voteContinued(storyId, direction, aTag, onAuthPopupCloseFunc) {
	aTag.onclick = null;
	$.ajax({ 
		url: "<c:url value="/story/vote"/>?storyId=" + storyId + "&direction=" + direction,
		type: "GET", 
		success: function(data) {
			$("#vote-story-" + storyId).html(data);
			if (typeof(onAuthPopupCloseFunc) == 'function') {
				onAuthPopupCloseFunc();
			}
		}
	});
}
</script>