src/main/java/com/sagg/domain/User.java
package com.sagg.domain;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.sagg.exception.ValidationFailedException;
import com.sagg.util.Globals;
import com.sagg.util.EmailUtil;
import com.sagg.util.StringUtil;

@Entity
@Table(name="USERS")
public class User extends DomainObject implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	private String email;
	private String username;
	private String password;
	private Integer type;
	private Boolean active;
	private Collection<Vote> votes;
	private Collection<Story> stories;
	private Collection<Bookmark> bookmarks;
    
    public User() {
    	type = Globals.USER_TYPE_REGULAR;
    }

	@Column(name = "EMAIL", unique=true, nullable = false, length = Globals.MAX_USER_EMAIL_LENGTH)
	public String getEmail() {
		return email;
	}
	
	public void setEmail(String email) {
		this.email = (email != null) ? email.trim() : null;
	}
	
	@Column(name = "USERNAME", unique=true, nullable = true, length = Globals.MAX_USER_USERNAME_LENGTH)
	public String getUsername() {
		return username;
	}
	
	public void setUsername(String name) {
		this.username = (name != null) ? name.trim() : null;
	}
	
	@Column(name = "PASSWORD", nullable = false, length = Globals.MAX_USER_PASSWORD_LENGTH)
	public String getPassword() {
		return password;
	}
	
	public void setPassword(String password) {
		this.password = password;
	}
	
	@Column(name = "TYPE", nullable = false)
	public Integer getType() {
		return type;
	}
	
	public void setType(Integer type) {
		this.type = type;
	}

	public Boolean getActive() {
		return active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}
	
	@OneToMany(cascade = {CascadeType.MERGE, CascadeType.REMOVE, CascadeType.REFRESH}, fetch=FetchType.EAGER, mappedBy="user")
	//TODO: JPA 2.0 supports new annotation: @MapKeyColumn(name="story_id") to create a Map<story_id, Vote> rather than a set
	public Collection<Vote> getVotes() {
		return votes;
	}
	
	//TODO: Mmm... think harder about redesigning this approach :(
	@Transient
	public Map<Integer, Vote> getVotesMap() { // Map<storyId, vote>
		return new HashMap<Integer, Vote>() {
			private static final long serialVersionUID = 1L;
			public Vote get(Object storyId) {
				Collection<Vote> votes = getVotes();
				if (votes != null) {
					for (Vote vote : votes) {
						if (storyId.equals(vote.getStory().getId())) {
							return vote;
						}
					}
				}
				return null;
			}
		};
	}
	
	@Transient
	public Collection<Vote> getVotesUp() {
		Collection<Vote> votesUp = new ArrayList<Vote>();
		if (votes != null) {
			for (Vote vote : votes) {
				if (vote.getVoteDirection().equals(Globals.VOTE_UP)) {
					votesUp.add(vote);
				}
			}
		}
		return votesUp;
	}
	
	@Transient
	public Collection<Vote> getVotesDown() {
		Collection<Vote> votesDown = new ArrayList<Vote>();
		if (votes != null) {
			for (Vote vote : votes) {
				if (vote.getVoteDirection().equals(Globals.VOTE_DOWN)) {
					votesDown.add(vote);
				}
			}
		}
		return votesDown;
	}

	public void setVotes(Collection<Vote> votes) {
		this.votes = votes;
	}

	@OneToMany(cascade = CascadeType.ALL, mappedBy="createdBy")
	public Collection<Story> getStories() {
		return stories;
	}
	
	public void setStories(Collection<Story> stories) {
		this.stories = stories;
	}
	
	@OneToMany(cascade = /*CascadeType.ALL*/ {CascadeType.MERGE, CascadeType.REMOVE, CascadeType.REFRESH}, fetch=FetchType.LAZY, mappedBy="user")
	public Collection<Bookmark> getBookmarks() {
		return bookmarks;
	}

	public void setBookmarks(Collection<Bookmark> bookmarks) {
		this.bookmarks = bookmarks;
	}
	
	@Transient
	public Collection<Story> getBookmarkedStories() {
		Collection<Story> stories = new ArrayList<Story>();
		for (Bookmark bookmark : bookmarks) {
			stories.add(bookmark.getStory());
		}
		return stories;
	}
	
	@Transient
	public Map<Integer, Bookmark> getBookmarksMap() {
		return new HashMap<Integer, Bookmark>() {
			private static final long serialVersionUID = 1L;
			public Bookmark get(Object storyId) {
				Collection<Bookmark> bookmarks = getBookmarks();
				if (bookmarks != null) {
					for (Bookmark bookmark : bookmarks) {
						if (storyId.equals(bookmark.getStory().getId())) {
							return bookmark;
						}
					}
				}
				return null;
			}
		};
	}

	//TODO: Move the validation methods out of the domain objects (UserValidator)
	//      This would make the code cleaner and allow us to have different validators for 
	//      the same object - it may be helpful sometimes. 
	public void validate() throws ValidationFailedException {
		if (!EmailUtil.isValidEmail(this.email)) {
			throw new ValidationFailedException("user.email", "err.email_invalid", "*** Invalid email. ***");
		}
		if (this.email.length() > Globals.MAX_USER_EMAIL_LENGTH) {
			throw new ValidationFailedException("user.email", "err.email_too_long", new String[]{""+Globals.MAX_USER_EMAIL_LENGTH}, "*** Email is too long. ***");
		}
		if (StringUtil.isEmpty(this.password)) {
			throw new ValidationFailedException("user.password", "err.password_empty", "*** Password can not be empty. ***");
		}
		if (this.password.length() > Globals.MAX_USER_PASSWORD_LENGTH) {
			throw new ValidationFailedException("user.password", "err.password_too_long", new String[]{""+Globals.MAX_USER_PASSWORD_LENGTH}, "*** Password is too long. ***");
		}
	}
	
	public String toString() {
		return this.email;
	}

}

src/main/java/com/sagg/web/form/ChangeUsernameForm.java
package com.sagg.web.form;

import com.sagg.domain.User;
import com.sagg.exception.ValidationFailedException;
import com.sagg.util.Globals;

public class ChangeUsernameForm {

	private User user = new User();
	private String username;
	
	public String getOldUsername() {
		return user.getUsername();
	}
	public void setOldUsername(String name) {
		this.user.setUsername(name);
	}
	
	public String getPassword() {
		return user.getPassword();
	}
	public void setPassword(String pass) {
		this.user.setPassword(pass);
	}
	
	public String getUsername() {
		return username;
	}
	public void setUsername(String name) {
		this.username = name;
	}
	
	public void validate() throws ValidationFailedException {
		if (getOldUsername().equals(this.username)) {
			throw new ValidationFailedException("username", "err.same_old_and_new_username", "*** The old and new usernames are the same. ***");
		}
		if (this.username.length() > Globals.MAX_USER_USERNAME_LENGTH) {
			throw new ValidationFailedException("username", "err.username_too_long", new String[]{""+Globals.MAX_USER_USERNAME_LENGTH}, "*** Username is too long. ***");
		}
	}
	
}

src/main/java/com/sagg/web/controller/UserController.java
package com.sagg.web.controller;

import javax.servlet.http.HttpSession;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import com.octo.captcha.service.CaptchaServiceException;
import com.octo.captcha.service.image.ImageCaptchaService;
import com.sagg.domain.User;
import com.sagg.exception.ValidationFailedException;
import com.sagg.service.UserService;
import com.sagg.util.Globals;
import com.sagg.web.Authorizable;
import com.sagg.web.UserSession;
import com.sagg.web.form.ChangeEmailForm;
import com.sagg.web.form.ChangePasswordForm;
import com.sagg.web.form.ChangeUsernameForm;
import com.sagg.web.form.FeedbackForm;
import com.sagg.web.form.RegistrationForm;

@Controller
@RequestMapping("/user")
public class UserController {
	
	private final UserService userService;
	private final ImageCaptchaService captchaService;

	@Autowired
	public UserController(UserService userService, ImageCaptchaService captchaService) {
		this.userService = userService;
		this.captchaService = captchaService;
	}

	
	
	/* (non-Javadoc)
	 * @see com.sagg.web.controller.UserController#logout(javax.servlet.http.HttpSession)
	 */
	@RequestMapping(value = "/logout", method = RequestMethod.GET)
	public String logout(HttpSession session) {
		session.removeAttribute(UserSession.ID);
		return "redirect:/main/story/list";
	}

	
	
	/* (non-Javadoc)
	 * @see com.sagg.web.controller.UserController#login(java.lang.String, org.springframework.ui.ModelMap)
	 */
	@RequestMapping(value = "/login", method = RequestMethod.GET)
	public String login(
			@RequestParam(value="signonForwardAction", required=false) String forwardAction,
			ModelMap modelMap) {
		modelMap.addAttribute("signonForwardAction", forwardAction);
		modelMap.addAttribute("maxEmailLength", Globals.MAX_USER_EMAIL_LENGTH);
		modelMap.addAttribute("maxPasswordLength", Globals.MAX_USER_PASSWORD_LENGTH);
		modelMap.addAttribute("user", new User());
		return "user/login";
	}

	/* (non-Javadoc)
	 * @see com.sagg.web.controller.UserController#login(java.lang.String, com.sagg.domain.User, org.springframework.validation.BindingResult, javax.servlet.http.HttpSession, org.springframework.ui.ModelMap)
	 */
	@RequestMapping(value = "/login", method = RequestMethod.POST)
	public String login(
			@RequestParam(value="signonForwardAction", required=false) String forwardAction, 
			User user, BindingResult result, HttpSession session /*WebRequest webRequest*/,
			ModelMap modelMap) throws Exception {

		modelMap.addAttribute("signonForwardAction", forwardAction);

		//TODO: hmm... this is error prone. If we follow this logic we shouldn't allow '@' in the username then.
		//      We can make a guess, if the entered string has the email format, TRY to find the user by email,
		//      if not found use it as the username.
		//If user entered username to log in, move it to the proper field:
		if (!user.getEmail().contains("@")) {
			user.setUsername(user.getEmail());
			user.setEmail(null);
		}
		String passEntered = user.getPassword();
		
		user = userService.login(user);
		if (user == null || !user.getPassword().equals(passEntered)) {
			result.rejectValue("email", "err.invalid_user_or_password", "*** Invalid User or Password ***");
			return "user/login";
		}
		if (user.getActive() == null || !user.getActive()) {
			result.rejectValue("email", "err.user_inactive", "*** User has not been activated ***");
			return "user/login";
		}
		addUserToSession(user, session);

		return "user/login";
	}
	
	
	/* (non-Javadoc)
	 * @see com.sagg.web.controller.UserController#loginex(java.lang.String, org.springframework.ui.ModelMap)
	 */
	@RequestMapping(value = "/loginex", method = RequestMethod.GET)
	public String loginex(
			@RequestParam(value="signonForwardAction", required=false) String forwardAction,
			ModelMap modelMap) throws Exception {

		modelMap.addAttribute("signonForwardAction", forwardAction);
		return "user/loginex";
	}

	
	/* (non-Javadoc)
	 * @see com.sagg.web.controller.UserController#show(javax.servlet.http.HttpSession, org.springframework.ui.ModelMap)
	 */
	@Authorizable
	@RequestMapping(value = "/show", method = RequestMethod.GET)
	public String show(HttpSession session, ModelMap modelMap) throws Exception {
		UserSession ses = (UserSession) session.getAttribute(UserSession.ID);
		User user = ses == null ? new User() : userService.getUser((ses).getUser().getId());
		modelMap.addAttribute("user", user);
		return "user/show";
	}

	

	//TODO: Rename to 'register' or 'create'! We don't have the 'edit' functionality for the user.
	/* (non-Javadoc)
	 * @see com.sagg.web.controller.UserController#edit(javax.servlet.http.HttpSession, org.springframework.ui.ModelMap)
	 */
	@RequestMapping(value = "/edit", method = RequestMethod.GET)
	public String edit(HttpSession session, ModelMap modelMap) throws Exception {
		RegistrationForm user = new RegistrationForm(); 
		modelMap.addAttribute("registrationForm", user);
		populateUserMaxLengths(modelMap);
		return "user/edit";
	}
	
	/* (non-Javadoc)
	 * @see com.sagg.web.controller.UserController#edit(com.sagg.web.form.RegistrationForm, org.springframework.validation.BindingResult, javax.servlet.http.HttpSession, org.springframework.ui.ModelMap, java.lang.String)
	 */
	@RequestMapping(value = "/edit", method = RequestMethod.POST)
	public String edit(
			RegistrationForm registrationForm, 
			BindingResult result, 
			HttpSession session,
			ModelMap modelMap,
			@RequestParam(value="signonForwardAction", required=false) String forwardAction) throws Exception {
		User user = registrationForm.getNewUser();
		populateUserMaxLengths(modelMap);
		
		try {
			registrationForm.validate();
		} catch (ValidationFailedException e) {
			result.rejectValue(e.getFieldName(), e.getErrorKey(), e.getParameters(), e.getMessage());
			return "user/edit";
		}
		
		if (!validateCaptcha(registrationForm.getCaptcha(), result, session.getId(), "err.captcha")) {
			return "user/edit";
		}
		
		if (userService.getUserByEmail(user.getEmail()) != null) {
			result.rejectValue("newUser.email", "err.user_email_already_exists", "*** User with this email already registered ***");
			return "user/edit";
		}
		
		if (userService.getUserByUsername(user.getUsername()) != null) {
			result.rejectValue("newUser.username", "err.user_username_already_exists", "*** User with this username already registered ***");
			return "user/edit";
		}
		
		userService.register(user);
		return "user/registered"; //At this stage the user is not logged in yet. They have to activate the account first.
	}
	
	private void populateUserMaxLengths(ModelMap modelMap) {
		modelMap.addAttribute("maxEmailLength", Globals.MAX_USER_EMAIL_LENGTH);
		modelMap.addAttribute("maxUsernameLength", Globals.MAX_USER_USERNAME_LENGTH);
		modelMap.addAttribute("maxPasswordLength", Globals.MAX_USER_PASSWORD_LENGTH);
	}
	
	
	
	/* (non-Javadoc)
	 * @see com.sagg.web.controller.UserController#activateAccount(java.lang.String, javax.servlet.http.HttpSession)
	 */
	@RequestMapping(value = "/activateAccount", method = RequestMethod.GET)
	public String activateAccount(@RequestParam(required=true) String uuid, 
			/*BindingResult result, */HttpSession session) throws Exception {
		User user = userService.activate(uuid);
		if (user == null || user.getActive() == null || !user.getActive()) {
//			result.reject("activation.failed", "*** Activation Failed! Either the key is invalid or the user has already been activated. ***");
			//TODO: Show an error message We cannot use a BindingResult object during the GET request :(
			return "redirect:/main/story/list";
		}
		addUserToSession(user, session);
		return "user/activated";
	}
	
	
	
	/* (non-Javadoc)
	 * @see com.sagg.web.controller.UserController#forgotPass(javax.servlet.http.HttpSession, org.springframework.ui.ModelMap)
	 */
	@RequestMapping(value = "/forgotPass", method = RequestMethod.GET)
	public String forgotPass(HttpSession session, ModelMap modelMap) throws Exception {
		modelMap.addAttribute("maxEmailLength", Globals.MAX_USER_EMAIL_LENGTH);
		modelMap.addAttribute("user", new User());
		return "user/forgotPass";
	}
	
	/* (non-Javadoc)
	 * @see com.sagg.web.controller.UserController#forgotPass(com.sagg.domain.User, org.springframework.validation.BindingResult, javax.servlet.http.HttpSession, org.springframework.ui.ModelMap)
	 */
	@RequestMapping(value = "/forgotPass", method = RequestMethod.POST)
	public String forgotPass(@ModelAttribute("user") User user, BindingResult result, HttpSession session, ModelMap modelMap) throws Exception {
		user = userService.login(user);
		
		if (user == null) {
			result.rejectValue("email", "err.email_invalid", "*** Invalid email ***");
			return "user/forgotPass";
		}
		
		
		
		/*
		 * TODO: Change password, and send the new pass to the user by email.
		 * 
		 * Problem: We can't change the password at this point because until we get a response to
		 * the email we have no guarantee that this is the owner of the account.
		 * 
		 * Perhaps we need to create a separate table, like the user activate table, that will 
		 * store requests for password changes, and the new generated passwords.
		 * 
		 * For now we will simply email the user their existing password.
		 */
		userService.sendPassword(user.getEmail());
		
		

		return "redirect:/main/story/list";
	}
	
	
	
	/* (non-Javadoc)
	 * @see com.sagg.web.controller.UserController#changePass(javax.servlet.http.HttpSession, org.springframework.ui.ModelMap)
	 */
	@RequestMapping(value = "/changePass", method = RequestMethod.GET)

src/main/webapp/WEB-INF/jsp/user/activated.jsp
<%@ include file="/WEB-INF/jsp/includes.jsp" %>
<%@ include file="/WEB-INF/jsp/header.jsp" %>

<div id="main">
	<h1><fmt:message key="create_user"/></h1>

	<p><fmt:message key="registration_completed"/></p>
	
	<div style="padding-left:15px; padding-bottom:40px;">
		<input type="button" value='<fmt:message key="ok"/>' class="button" onclick="document.location.href = '<c:url value="/"/>'">
	</div>
</div>

<%@ include file="/WEB-INF/jsp/footer.jsp" %>
 
 

src/main/webapp/WEB-INF/jsp/user/changeEmail.jsp
<%@ page contentType="text/html; charset=UTF-8" isELIgnored="false" %>
<%@ include file="/WEB-INF/jsp/includes.jsp" %>

<c:choose>
<c:when test="${emailChanged}">

	<script type="text/javascript">
		window.location.reload(true);
	</script>
	
</c:when>
<c:otherwise>

	<h1><fmt:message key="change_email"/></h1>
	
	<form:form modelAttribute="changeEmailForm" method="POST">
		<table class="form centered">
			<tr>
				<td class="formLabel"><fmt:message key="email"/>:</td>
				<td class="formLabel" style="height:30px;">
					<c:out value="${changeEmailForm.oldEmail}"/>
					<input type="hidden" id="oldEmail" name="oldEmail" value="${changeEmailForm.oldEmail}"/>
				</td>
			</tr>
			
			
			<tr>
				<td class="formLabel"><fmt:message key="new_email"/>:</td>
				<td><form:input path="email" id="email" cssClass="formInput" onkeyup="executeIfEnter(event, 'changeEmail()');"/></td>
			</tr>
			<tr>
				<td></td>
				<td><form:errors path="email" cssClass="errors"/></td>
			</tr>
			
			
			<tr>
				<td class="formLabel"><fmt:message key="password"/>:</td>
				<td><form:password path="password" cssClass="formInput" onkeyup="executeIfEnter(event, 'changeEmail()');"/></td>
			</tr>
			<tr>
				<td></td>
				<td><form:errors path="password" cssClass="errors"/></td>
			</tr>
		</table>
		<br/>
		
		<input type="button" onclick="changeEmail()" value="<fmt:message key="change"/>" class="button"/>
		<input type="button" onclick="$('#changeEmailPopupId').dialog('close');" value='<fmt:message key="cancel"/>' class="button">
	</form:form>
	
	<script type="text/javascript">
		document.getElementById('email').focus();
	
		function changeEmail() {
			var url = '<c:url value="/user/changeEmail"/>';
			var params = "oldEmail=" + $("#oldEmail").val() +"&email=" + $("#email").val() + "&password=" + $("#password").val();
			var resultContainerId = 'changeEmailPopupId';
			ajaxPost(url, params, resultContainerId);
		}
	</script>

</c:otherwise>
</c:choose>

src/main/webapp/WEB-INF/jsp/user/changePass.jsp
<%@ page contentType="text/html; charset=UTF-8" isELIgnored="false" %>
<%@ include file="/WEB-INF/jsp/includes.jsp" %>

<c:choose>
<c:when test="${passwordChanged}">

	<script type="text/javascript">
		window.location.reload(true);
	</script>
	
</c:when>
<c:otherwise>
	
	<h1><fmt:message key="change_password"/></h1>
	
	<form:form modelAttribute="changePassForm" method="POST" onsubmit="return getConfirmPassState();">
		<table class="form centered">
			<tr>
				<td class="formLabel"><fmt:message key="old_password"/>:</td>
				<td><form:password path="oldPassword" id="oldPassword" cssClass="formInput" onkeyup="executeIfEnter(event, 'changePass()');"/></td>
			</tr>
			<tr>
				<td></td>
				<td><form:errors path="oldPassword" cssClass="errors"/></td>
			</tr>
			
			
			<tr>
				<td class="formLabel"><fmt:message key="new_password"/>:</td>
				<td><form:password path="password" id="firstPassword" cssClass="formInput" onkeyup="executeIfEnter(event, 'changePass()');"/></td>
			</tr>
			<tr>
				<td></td>
				<td><form:errors path="password" cssClass="errors"/></td>
			</tr>
			
			
			<tr>
				<td class="formLabel"><fmt:message key="confirm_new_password"/>:</td>
				<td><input type="password" id="confirmPassword" class="formInput" onfocus="updateConfirmPassState()" onblur="hideConfirmPassState()" onkeyup="updateConfirmPassState(); executeIfEnter(event, 'changePass()');"/></td>
			</tr>
			<tr>
				<td></td>
				<td class="errors" id="confirmPasswordState" style="height:20px;"></td>
			</tr>
		</table>
		<br/>
		
		<input type="button" onclick="changePass()" value="<fmt:message key="change"/>" class="button"/>
		<input type="button" onclick="$('#changePassPopupId').dialog('close');" value='<fmt:message key="cancel"/>' class="button">
	</form:form>
	
	
	<script type="text/javascript">
		document.getElementById('oldPassword').focus();
	
		function changePass() {
			if (getConfirmPassState()) {
				var url = '<c:url value="/user/changePass"/>';
				var params = "oldPassword=" + $("#oldPassword").val() + "&password=" + $("#firstPassword").val();
				var resultContainerId = 'changePassPopupId';
				ajaxPost(url, params, resultContainerId);
			}
		}
	</script>
	<%@ include file="/WEB-INF/jsp/user/confirmPass_js.jsp" %>

</c:otherwise>
</c:choose>

src/main/webapp/WEB-INF/jsp/user/changeUsername.jsp
<%@ page contentType="text/html; charset=UTF-8" isELIgnored="false" %>
<%@ include file="/WEB-INF/jsp/includes.jsp" %>

<c:choose>
<c:when test="${usernameChanged}">

	<script type="text/javascript">
		window.location.reload(true);
	</script>
	
</c:when>
<c:otherwise>

	<h1><fmt:message key="change_username"/></h1>
	
	<form:form modelAttribute="changeUsernameForm" method="POST">
		<table class="form centered">
			<tr>
				<td class="formLabel"><fmt:message key="username"/>:</td>
				<td class="formLabel" style="height:30px;">
					<c:out value="${changeUsernameForm.oldUsername}"/>
					<input type="hidden" id="oldUsername" name="oldUsername" value="${changeUsernameForm.oldUsername}"/>
				</td>
			</tr>
			
			
			<tr>
				<td class="formLabel"><fmt:message key="new_username"/>:</td>
				<td><form:input path="username" id="username" cssClass="formInput" onkeyup="executeIfEnter(event, 'changeUsername()');"/></td>
			</tr>
			<tr>
				<td></td>
				<td><form:errors path="username" cssClass="errors"/></td>
			</tr>
			
			
			<tr>
				<td class="formLabel"><fmt:message key="password"/>:</td>
				<td><form:password path="password" cssClass="formInput" onkeyup="executeIfEnter(event, 'changeUsername()');"/></td>
			</tr>
			<tr>
				<td></td>
				<td><form:errors path="password" cssClass="errors"/></td>
			</tr>
		</table>
		<br/>
		
		<input type="button" onclick="changeUsername()" value="<fmt:message key="change"/>" class="button"/>
		<input type="button" onclick="$('#changeUsernamePopupId').dialog('close');" value='<fmt:message key="cancel"/>' class="button">
	</form:form>
	
	<script type="text/javascript">
		document.getElementById('username').focus();
	
		function changeUsername() {
			var url = '<c:url value="/user/changeUsername"/>';
			var params = "oldUsername=" + $("#oldUsername").val() +"&username=" + $("#username").val() + "&password=" + $("#password").val();
			var resultContainerId = 'changeUsernamePopupId';
			ajaxPost(url, params, resultContainerId);
		}
	</script>

</c:otherwise>
</c:choose>

src/main/webapp/WEB-INF/jsp/user/confirmPass_js.jsp
<script type="text/javascript">
var confPassValid = true;

function hideConfirmPassState() {
	document.getElementById('confirmPasswordState').innerHTML = '';
}

function updateConfirmPassState() {
	confPassValid = (document.getElementById('firstPassword').value == 
					document.getElementById('confirmPassword').value);
	var confPassDiv = document.getElementById('confirmPasswordState');
	var msg = '';
	if (confPassValid) {
		confPassDiv.className = "";
		confPassDiv.innerHTML = '<fmt:message key="confirm_password_pass"/>';
	} else {
		confPassDiv.className = "errors";
		confPassDiv.innerHTML = '<fmt:message key="confirm_password_fail"/>';
	}
}

function getConfirmPassState() {
	updateConfirmPassState();
	return confPassValid;
}
</script>

src/main/webapp/WEB-INF/jsp/user/forgotPass.jsp
<%@ include file="/WEB-INF/jsp/includes.jsp" %>
<%@ include file="/WEB-INF/jsp/header.jsp" %>

<div id="main">

<form:form modelAttribute="user" method="POST">

<h1><fmt:message key="password_reset"/></h1>

<p style="padding:10px; padding-bottom: 0px;">
	<fmt:message key="forgot_pass_message"/>
</p>

<table class="form" style="padding:10px; padding-bottom: 15px;">
	<tr>
		<td class="formLabel"><fmt:message key="email"/>:</td>
		<td><form:input path="email" cssClass="formInput" maxlength="${maxEmailLength}"/></td>
	</tr>
	<tr>
		<td></td>
		<td><form:errors path="email" cssClass="errors"/></td>
	</tr>
</table>
<br/>

<div style="padding-left:15px; padding-bottom:40px;">
	<input type="submit" value="<fmt:message key="submit"/>" class="button">
	<input type="button" value='<fmt:message key="cancel"/>' class="button" onclick="document.location.href = '<c:url value="/story/list"/>'">
</div>

</form:form>

</div>

<%@ include file="/WEB-INF/jsp/footer.jsp" %>
 
 

src/main/webapp/WEB-INF/jsp/user/registered.jsp
<%@ include file="/WEB-INF/jsp/includes.jsp" %>
<%@ include file="/WEB-INF/jsp/header.jsp" %>

<div id="main">
	<h1><fmt:message key="create_user"/></h1>

	<p style="height:100px;"><fmt:message key="confirmation_email"/></p>
	
	<div style="padding-left:15px; padding-bottom:40px;">
		<input type="button" value='<fmt:message key="ok"/>' class="button" onclick="document.location.href = '<c:url value="/"/>'">
	</div>
</div>

<%@ include file="/WEB-INF/jsp/footer.jsp" %>
 